spring.datasource.url=jdbc:postgresql://ep-still-pine-apj9bjvw.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cDK8OvB9bQsF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true